### PR TITLE
feat(init): accept dir argument, not always cwd

### PR DESCRIPTION
**Pull request by yajo**
This will help integrating with pre-commit on nonstandard repo structures, such as Doodba ones.

@moduon MT-1075

### CODE REVIEW

**Comment by yajo** [comment]
@sbidoul it seems CI failure was already there

**Comment by sbidoul** [comment]
Makes sense and looks good, thanks. Can you add a `news/21.feature` with a changelog entry?

**Comment by yajo** [comment]
Isn't it already?

**Comment by sbidoul** [comment]
> Isn't it already?

Yup :facepalm:

**Pull request merged**
